# Generated by Django 2.2.10 on 2020-06-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_id',
            field=models.CharField(default='null', help_text='Gatekeeper User Auth ID', max_length=24, unique=True),
            preserve_default=False,
        ),
    ]
