# Generated by Django 2.1.2 on 2019-05-09 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('NA', 'Prefer not to disclose')], max_length=2)),
                ('classification', models.CharField(choices=[('U1', 'U1'), ('U2', 'U2'), ('U3', 'U3'), ('U4', 'U4'), ('U5', 'U5')], max_length=2)),
                ('grad_year', models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], verbose_name='graduation year')),
                ('dietary_restrictions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Halal', 'Halal'), ('Kosher', 'Kosher'), ('Food Allergies', 'Food Allergies')], max_length=44, verbose_name='dietary restrictions')),
                ('travel_reimbursement_required', models.BooleanField(default=False)),
                ('num_hackathons_attended', models.PositiveSmallIntegerField(default=0)),
                ('previous_attendant', models.BooleanField(default=False)),
                ('tamu_student', models.BooleanField(default=True)),
                ('interests', models.TextField(max_length=200)),
                ('essay1', models.TextField(max_length=200)),
                ('essay2', models.TextField(blank=True, max_length=200, null=True)),
                ('essay3', models.TextField(blank=True, max_length=200, null=True)),
                ('essay4', models.TextField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Provide any additional notes and/or comments in the text box provide', max_length=300)),
                ('resume', models.FileField(blank=True, null=True, upload_to='hacker_resumes')),
                ('approved', models.NullBooleanField()),
                ('queued_for_approval', models.NullBooleanField()),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('date_queued_for_approval', models.DateField(blank=True, null=True)),
                ('date_submitted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, verbose_name='shirt size')),
                ('notes', models.TextField(blank=True, help_text='Provide any additional notes and/or comments in the text box provide', max_length=300)),
                ('date_confirmed', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='HackerProfile',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='admitted',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='admitted_datetime',
        ),
        migrations.AddField(
            model_name='hacker',
            name='confirm_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='hacker',
            name='email_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='hacker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hacker.Team'),
        ),
        migrations.AddField(
            model_name='application',
            name='hacker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
