# Generated by Django 2.1.2 on 2018-10-21 05:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0002_auto_20181020_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='dietary_restrictions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Vegan', 'Vegan'), ('Vegaterian', 'Vegarterian'), ('Halal', 'Halal'), ('Kosher', 'Kosher'), ('Food Allergies', 'Food Allergies')], max_length=44, verbose_name='Dietary Restrictions'),
        ),
    ]
