# Generated by Django 2.1.2 on 2019-05-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0002_auto_20190509_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hacker',
            name='confirm_code',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='email_confirmed',
        ),
        migrations.AlterField(
            model_name='hacker',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last name'),
        ),
    ]
