# Generated by Django 2.1.2 on 2019-05-10 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0003_auto_20190510_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='hacker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL),
        ),
    ]
