# Generated by Django 2.1.2 on 2018-10-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0004_auto_20181021_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, help_text='Provide any additional notes and/or comments in the text box provide', max_length=300),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='notes',
            field=models.TextField(blank=True, help_text='Provide any additional notes and/or comments in the text box provide', max_length=300),
        ),
    ]
