# Generated by Django 2.2.4 on 2019-10-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_rsvp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='shirt_size',
            field=models.CharField(choices=[(None, '-- Select Option --'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='transport_type',
            field=models.CharField(choices=[(None, '-- Select Option --'), ('drive', 'Driving'), ('bus-tu', 'TAMUhack Bus - UT Austin'), ('bus-utd', 'TAMUhack Bus - UTD'), ('bus-uta', 'TAMUhack Bus - UTA'), ('bus-utsa', 'TAMUhack Bus - UTSA'), ('bus-utrgv', 'TAMUhack Bus - UTRGV'), ('other-bus', 'Other Bus (Greyhound, Megabus, etc.)'), ('walk-cycle', 'Walking/Cycling')], max_length=10),
        ),
    ]
