from datetime import date

EVENT_NAME = "Howdy Hack"
EMAIL_CONFIRM_CODE_LENGTH = 6
MAX_YEARS_ADMISSION = 6
DAYS_TO_RSVP = 7

REGISTRATION_OPEN = date(2019, 7, 20)
REGISTRATION_CLOSE = date(2019, 7, 27)
CONFIRMATION_CLOSE = date(2019, 8, 3)
