# Generated by Django 2.2.4 on 2019-10-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='walk_in',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wave',
            name='is_walk_in_wave',
            field=models.BooleanField(default=False, verbose_name='Is this wave for walk-ins?'),
        ),
    ]
