# Generated by Django 2.2.10 on 2020-06-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='question1',
            field=models.TextField(blank=True, max_length=500, verbose_name='What prize(s) do you want to see at TD?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question2',
            field=models.TextField(blank=True, max_length=500, verbose_name='What workshop(s) do you want to see at TD?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question3',
            field=models.TextField(blank=True, max_length=500, verbose_name='Have you taken any data science or machine learning related classes?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question4',
            field=models.TextField(blank=True, max_length=500, verbose_name='Are you involved in any data science or machine learning related clubs on campus?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question5',
            field=models.TextField(blank=True, max_length=500, verbose_name='Have you had any data science or machine learning related jobs/internships?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question6',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
