# Generated by Django 2.2.4 on 2019-10-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20191008_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='question3',
            field=models.TextField(max_length=500, verbose_name="What is a cool prize you'd like to win at HowdyHack?"),
        ),
    ]
