# Generated by Django 2.2.10 on 2020-06-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200623_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='industries_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='other-industries'),
        ),
    ]
