# Generated by Django 2.2.4 on 2019-10-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20191002_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='walk_in',
        ),
    ]
