# Generated by Django 2.2.10 on 2020-02-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200217_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='school_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
