# Generated by Django 2.2.4 on 2019-10-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190930_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='is_walk_in_wave',
            field=models.BooleanField(default=False, verbose_name='Is this wave for walk-ins?'),
        ),
    ]
