# Generated by Django 2.2.8 on 2020-02-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200211_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='school',
            field=models.ForeignKey(on_delete='What school do you go to?', to='application.School'),
        ),
    ]
