# Generated by Django 2.2.4 on 2019-09-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190922_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user_email',
            field=models.TextField(default='fake@fake.com', max_length=500, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
