# Generated by Django 2.2.10 on 2020-06-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_industries_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='physical_location_other',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='other-physical-location'),
        ),
    ]
