# Generated by Django 2.2.10 on 2020-04-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_dietaryrestriction"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="dietary_restrictions_other",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Self-describe"
            ),
        ),
        migrations.RemoveField(
            model_name="application",
            name="dietary_restrictions",
        ),
        migrations.AddField(
            model_name="application",
            name="dietary_restrictions",
            field=models.ManyToManyField(to="application.DietaryRestriction"),
        ),
    ]
