# Generated by Django 2.2.10 on 2020-06-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200623_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='extra_links',
            field=models.TextField(blank=True, max_length=500, verbose_name="Is there anything else you'd like us to look at while considering your application?"),
        ),
        migrations.AlterField(
            model_name='application',
            name='question3',
            field=models.TextField(blank=True, max_length=500, verbose_name='What data science or machine learning related classes have you taken, if any?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question5',
            field=models.TextField(blank=True, max_length=500, verbose_name='What data science or machine learning related jobs/internships have you had, if any?'),
        ),
    ]
