# Generated by Django 2.2.10 on 2020-08-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200413_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, to='application.DietaryRestriction'),
        ),
    ]
