# Generated by Django 2.2.4 on 2019-10-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20191020_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last name'),
        ),
    ]
