# Generated by Django 2.2.13 on 2020-08-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200809_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='question3',
            field=models.TextField(max_length=500, verbose_name="What is a cool prize you'd like to win at Hacklahoma?"),
        ),
        migrations.AlterField(
            model_name='application',
            name='transport_needed',
            field=models.CharField(choices=[('D', 'Driving'), ('B', 'Hacklahoma Bus'), ('BUT', 'Hacklahoma Bus - UT Austin'), ('BUTD', 'Hacklahoma Bus - UT Dallas'), ('BUTA', 'Hacklahoma Bus - UT Arlington'), ('BUTSA', 'Hacklahoma Bus - UTSA'), ('BUTRGV', 'Hacklahoma Bus - UTRGV'), ('OB', 'Other Bus (Greyhound, Megabus, etc.)'), ('F', 'Flying'), ('P', 'Public Transportation'), ('M', 'Walking/Biking')], max_length=11, verbose_name='How will you be getting to the event?'),
        ),
    ]
