# Generated by Django 2.2.10 on 2020-06-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200625_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='question6',
            new_name='interesting_industries',
        ),
        migrations.RemoveField(
            model_name='application',
            name='learner',
        ),
        migrations.AlterField(
            model_name='application',
            name='shirt_size',
            field=models.CharField(choices=[('XXS', 'Unisex XXS'), ('XS', 'Unisex XS'), ('S', 'Unisex S'), ('M', 'Unisex M'), ('L', 'Unisex L'), ('XL', 'Unisex XL'), ('XXL', 'Unisex XXL')], help_text='Being an online event, we cannot promise everyone a t-shirt. However, we’ll try our best to get them to you.', max_length=4, verbose_name='What size shirt do you wear?'),
        ),
    ]
