# Generated by Django 2.2.10 on 2020-06-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20200625_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='question3',
            new_name='ds_ml_classes',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='question4',
            new_name='ds_ml_clubs',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='question5',
            new_name='ds_ml_jobs',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='question1',
            new_name='prize_suggestions',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='question2',
            new_name='workshop_suggestions',
        ),
    ]
