# Generated by Django 2.2.13 on 2020-09-14 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200809_2037'),
        ('application', '0007_auto_20200913_2240'),
    ]

    operations = [
    ]
