# Generated by Django 2.2.10 on 2020-06-26 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20200625_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='shirt_size',
        ),
    ]
