# Generated by Django 2.2.13 on 2020-09-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20200831_0328'),
        ('application', '0009_auto_20200914_0355'),
    ]

    operations = [
    ]
