# Generated by Django 2.2.10 on 2020-06-29 17:03

import django.core.validators
from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_remove_application_shirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, help_text='Companies will use this resume to offer interviews for internships and full-time positions.', null=True, storage=django_s3_storage.storage.S3Storage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Upload your resume (PDF only)'),
        ),
    ]
