# Generated by Django 2.2.13 on 2020-11-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0009_application_technology_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="hackathon_purpose",
            field=models.CharField(
                choices=[
                    ("W", "I want to win!"),
                    ("L", "I want to learn something new!"),
                    ("WR", "I just want to attend all the workshops"),
                    (
                        "R",
                        "I literally signed up to talk to the awesome sponsors and get a job",
                    ),
                    ("M", "I want to just mess around on the Minecraft server!"),
                ],
                default="",
                max_length=16,
                verbose_name="What is your main purpose for registering for this event?",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="has_team",
            field=models.CharField(
                choices=[("HT", "I do have a team"), ("HNT", "I do not have a team")],
                default=("HNT", "I do not have a team"),
                max_length=16,
                verbose_name="Do you have a team yet?",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="wants_team",
            field=models.CharField(
                choices=[
                    ("WT", "I would like you to make me a team"),
                    ("DWT", "I would not like for you to make me a team"),
                ],
                default=("WT", "I would like you to make me a team"),
                help_text="We will take into account many factors to make sure you are paired with a team that works well",
                max_length=16,
                verbose_name="Would you like to be paired with a hand-crafted team",
            ),
        ),
    ]
