# Generated by Django 2.2.13 on 2020-09-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_merge_20200926_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='transport_needed',
            field=models.CharField(choices=[('D', 'Driving'), ('OB', 'Bus (Greyhound, Megabus, etc.)'), ('F', 'Flying'), ('P', 'Public Transportation'), ('M', 'Walking/Biking')], max_length=11, verbose_name='How will you be getting to the event?'),
        ),
    ]
