# Generated by Django 2.2.13 on 2020-10-22 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20200926_2328'),
        ('application', '0009_merge_20200926_2305'),
    ]

    operations = [
    ]
