# Generated by Django 2.2.13 on 2020-10-26 04:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20201021_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_level_study',
            field=models.CharField(choices=[('H', 'High school'), ('T', 'Tech school'), ('U', 'Undergrad univsity'), ('G', 'Graduate university')], default='NA', max_length=2, verbose_name='What is your most current level of study?'),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.CharField(default='N/A', max_length=255, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default='0', max_length=255, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='application',
            name='pronouns',
            field=models.CharField(default='N/A', max_length=255, verbose_name='pronouns'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('NA', 'Prefer not to answer'), ('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('X', 'Other')], default='NA', max_length=2, verbose_name="What's your gender?"),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='application',
            name='grad_year',
            field=models.IntegerField(choices=[('N', 'N/A'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], verbose_name='What is your anticipated graduation year?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question1',
            field=models.TextField(max_length=500, verbose_name='Why is the history of computing so important?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question2',
            field=models.TextField(max_length=500, verbose_name='What workshops do you want to see at Hacklahoma?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question3',
            field=models.TextField(max_length=500, verbose_name='What kind of prizes do you want to see at Hacklahoma?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='race',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AI', 'American Indian or Alaskan Native'), ('AS', 'Asian'), ('BL', 'Black or African-American'), ('HI', 'Hispanic or Latino'), ('NH', 'Native Hawaiian or other Pacific Islander'), ('WH', 'White'), ('NA', 'Prefer not to answer'), ('O', 'Other')], max_length=41, verbose_name='What race(s) do you identify with?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='race_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='application',
            name='shirt_size',
            field=models.CharField(choices=[('XXS', 'Unisex XXS'), ('XS', 'Unisex XS'), ('S', 'Unisex S'), ('M', 'Unisex M'), ('L', 'Unisex L'), ('XL', 'Unisex XL'), ('XXL', 'Unisex XXL')], max_length=4, verbose_name='What size shirt do you wear?'),
        ),
    ]
