# Generated by Django 2.2.13 on 2020-12-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20201208_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='agree_to_mlh_stuff',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None),
        ),
    ]
