# Generated by Django 2.2.13 on 2020-12-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0014_auto_20201223_1832"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="technology_experience",
            field=models.CharField(default=None, max_length=450),
        ),
    ]
