# Generated by Django 2.2.13 on 2020-12-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_application_agree_to_mlh_stuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='agree_to_mlh_stuff',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, null=True),
        ),
    ]
