# Generated by Django 2.2.13 on 2020-10-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20201026_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='application',
            name='extra_links',
            field=models.CharField(blank=True, max_length=200, verbose_name="Point us to any social links you'd like us to look at while considering your application"),
        ),
        migrations.AlterField(
            model_name='application',
            name='num_hackathons_attended',
            field=models.CharField(max_length=3, verbose_name='How many hackathons have you attended?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='phone number'),
        ),
    ]
