# Generated by Django 2.2.13 on 2020-12-24 00:17

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20201223_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=address.models.AddressField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
