# Generated by Django 2.2.13 on 2020-10-26 19:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20201026_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hear_about',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SM', 'Social media'), ('FR', 'Friend'), ('EM', 'Email'), ('FL', 'Flyer'), ('IC', 'In class'), ('ML', 'Major League Hacking'), ('O', 'Other')], max_length=41, null=True, verbose_name='How did you hear about Hacklahoma?'),
        ),
        migrations.AddField(
            model_name='application',
            name='hear_about_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other'),
        ),
    ]
