# Generated by Django 2.2.13 on 2020-10-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20201026_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='classification',
        ),
    ]
