# Generated by Django 2.2.13 on 2023-12-03 23:08

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20230807_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='emergency_contact_email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Emergency Contact Email'),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Emergency Contact Phone Number'),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=255, verbose_name='Emergency Contact Relationship'),
        ),
        migrations.AlterField(
            model_name='application',
            name='num_hackathons_attended',
            field=models.CharField(choices=[('0', 'This will be my first!'), ('1', '1'), ('2-3', '2-3'), ('4-5', '4-5'), ('6+', '6+')], max_length=22, verbose_name='How many hackathons have you attended?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='race',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AI', 'American Indian or Alaskan Native'), ('ASI', 'Asian (Indian Subcontinent)'), ('ASE', 'Asian (East Asia)'), ('ASSE', 'Asian (Southeast Asia)'), ('AS', 'Asian (Other)'), ('BL', 'Black or African-American'), ('HI', 'Hispanic or Latino'), ('NH', 'Native Hawaiian or other Pacific Islander'), ('WH', 'White'), ('NA', 'Prefer not to answer'), ('O', 'Prefer to self-describe')], max_length=41, verbose_name='What race(s) do you identify with?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='wants_team',
            field=models.CharField(choices=[('Friend', 'From a friend'), ('Tabling', 'Tabling outside Zachry'), ('Yard Sign', 'Yard sign'), ('Social Media', 'Social media'), ('Student Orgs', 'Though another student org'), ('TH Organizer', 'From a TAMUhack organizer'), ('ENGR Newsletter', 'From the TAMU Engineering Newsletter'), ('MLH', 'Major League Hacking (MLH)'), ('Attended Before', "I've attended TAMUhack before")], max_length=16, verbose_name='How did you hear about TAMUhack?'),
        ),
    ]
