# Generated by Django 2.2.13 on 2020-12-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20201223_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='agree_to_mlh_stuff',
            field=models.BooleanField(blank=True, choices=[(True, 'Agree')], default=None, null=True),
        ),
    ]
