# Generated by Django 2.2.13 on 2020-10-30 07:40

import application.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_auto_20201030_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='additional_accommodations',
            field=models.TextField(blank=True, max_length=500, verbose_name='Do you require any special accommodations at the event?'),
        ),
        migrations.AddField(
            model_name='application',
            name='agree_to_coc',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None),
        ),
        migrations.AddField(
            model_name='application',
            name='birthday',
            field=models.CharField(max_length=255, null=True, verbose_name='birth day'),
        ),
        migrations.AddField(
            model_name='application',
            name='confirmation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, to='application.DietaryRestriction'),
        ),
        migrations.AddField(
            model_name='application',
            name='dietary_restrictions_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Self-describe'),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.CharField(max_length=255, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('NA', 'Prefer not to answer'), ('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('X', 'Other')], default='NA', max_length=2, verbose_name="What's your gender?"),
        ),
        migrations.AddField(
            model_name='application',
            name='gender_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other'),
        ),
        migrations.AddField(
            model_name='application',
            name='graduation_year',
            field=models.IntegerField(choices=[('N', 'N/A'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], null=True, verbose_name='What is your anticipated graduation year?'),
        ),
        migrations.AddField(
            model_name='application',
            name='interested_in_hacklahoma',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, verbose_name='Are you interesetd in joining the Hacklahoma 2022 team?'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_adult',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, help_text='Please note that freshmen under 18 must be accompanied by an adult or prove that they go to Texas A&M.', verbose_name='Please confirm you are 18 or older.'),
        ),
        migrations.AddField(
            model_name='application',
            name='level_of_study',
            field=models.CharField(choices=[('H', 'High school'), ('T', 'Tech school'), ('U', 'Undergrad univsity'), ('G', 'Graduate university')], default='NA', max_length=2, verbose_name='What is your most current level of study?'),
        ),
        migrations.AddField(
            model_name='application',
            name='liability_waiver',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, verbose_name='Liability Waiver'),
        ),
        migrations.AddField(
            model_name='application',
            name='major',
            field=models.CharField(max_length=255, null=True, verbose_name="What's your major?"),
        ),
        migrations.AddField(
            model_name='application',
            name='mlh_authorize',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, verbose_name='I authorize Major League Hacking to send me occasional messages about hackathons.'),
        ),
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, max_length=300, verbose_name='Anything else you would like us to know?'),
        ),
        migrations.AddField(
            model_name='application',
            name='num_hackathons_attended',
            field=models.IntegerField(null=True, verbose_name='How many hackathons have you attended?'),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.IntegerField(null=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='application',
            name='photo_release',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, verbose_name='I agree to have '),
        ),
        migrations.AddField(
            model_name='application',
            name='pronouns',
            field=models.CharField(default='', max_length=255, verbose_name='pronouns'),
        ),
        migrations.AddField(
            model_name='application',
            name='question1',
            field=models.TextField(max_length=500, null=True, verbose_name='Why is the history of computing so important?'),
        ),
        migrations.AddField(
            model_name='application',
            name='question2',
            field=models.TextField(max_length=500, null=True, verbose_name='What workshops do you want to see at Hacklahoma?'),
        ),
        migrations.AddField(
            model_name='application',
            name='question3',
            field=models.TextField(max_length=500, null=True, verbose_name='What kind of prizes do you want to see at Hacklahoma?'),
        ),
        migrations.AddField(
            model_name='application',
            name='race',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AI', 'American Indian or Alaskan Native'), ('AS', 'Asian'), ('BL', 'Black or African-American'), ('HI', 'Hispanic or Latino'), ('NH', 'Native Hawaiian or other Pacific Islander'), ('WH', 'White'), ('NA', 'Prefer not to answer'), ('O', 'Other')], max_length=41, null=True, verbose_name='What race(s) do you identify with?'),
        ),
        migrations.AddField(
            model_name='application',
            name='race_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other'),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(help_text='Companies will use this resume to offer interviews for internships and full-time positions.', null=True, upload_to=application.models.uuid_generator, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Upload your resume (PDF only)'),
        ),
        migrations.AddField(
            model_name='application',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.School', verbose_name='What school do you go to?'),
        ),
        migrations.AddField(
            model_name='application',
            name='school_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='shirt_size',
            field=models.CharField(choices=[('XXS', 'Unisex XXS'), ('XS', 'Unisex XS'), ('S', 'Unisex S'), ('M', 'Unisex M'), ('L', 'Unisex L'), ('XL', 'Unisex XL'), ('XXL', 'Unisex XXL')], max_length=4, null=True, verbose_name='What size shirt do you wear?'),
        ),
        migrations.AddField(
            model_name='application',
            name='social_links',
            field=models.CharField(blank=True, max_length=200, verbose_name="Point us to any social links you'd like us to look at while considering your application"),
        ),
        migrations.AddField(
            model_name='application',
            name='transport_needed',
            field=models.CharField(choices=[('D', 'Driving'), ('OB', 'Bus (Greyhound, Megabus, etc.)'), ('F', 'Flying'), ('P', 'Public Transportation'), ('M', 'Walking/Biking')], max_length=11, null=True, verbose_name='How will you be getting to the event?'),
        ),
        migrations.AddField(
            model_name='application',
            name='travel_reimbursement',
            field=models.BooleanField(default=False, help_text='Travel reimbursement is only provided if you stay the whole time and submit a project.', verbose_name="I'd like to apply for travel reimbursement"),
        ),
        migrations.AddField(
            model_name='application',
            name='where_did_you_hear',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SM', 'Social media'), ('FR', 'Friend'), ('EM', 'Email'), ('FL', 'Flyer'), ('IC', 'In class'), ('ML', 'Major League Hacking'), ('O', 'Other')], max_length=41, null=True, verbose_name='How did you hear about Hacklahoma?'),
        ),
        migrations.AddField(
            model_name='application',
            name='where_did_you_hear_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other'),
        ),
    ]
