# Generated by Django 2.2.13 on 2020-10-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_remove_application_transport_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='graduation_year',
            field=models.CharField(choices=[('N', 'N/A'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=4, null=True, verbose_name='What is your anticipated graduation year?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='num_hackathons_attended',
            field=models.CharField(max_length=2, null=True, verbose_name='How many hackathons have you attended?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='phone number'),
        ),
    ]
