# Generated by Django 2.2.13 on 2020-10-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_auto_20201030_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='photo_release',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, verbose_name="I authorize Hacklahoma to release and photo's with me in it."),
        ),
    ]
