# Generated by Django 2.2.13 on 2020-10-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20201030_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='additional_accommodations',
        ),
        migrations.AlterField(
            model_name='application',
            name='interested_in_hacklahoma',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, verbose_name='Are you interested in joining the Hacklahoma 2022 team?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='level_of_study',
            field=models.CharField(choices=[('H', 'High school'), ('T', 'Tech school'), ('U', 'Undergrad university'), ('G', 'Graduate university')], default='NA', max_length=2, verbose_name='What is your most current level of study?'),
        ),
    ]
