# Generated by Django 2.2.13 on 2020-10-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20201030_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='application',
            name='dietary_restrictions_other',
        ),
    ]
