# Generated by Django 2.2.13 on 2024-11-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0025_auto_20241024_1250"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="accessibility_requirements",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Agree"), (False, "Disagree")],
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="agree_to_photos",
            field=models.BooleanField(
                choices=[(True, "Agree")], default=None, null=True
            ),
        ),
    ]
