# Generated by Django 2.2.13 on 2020-10-30 13:06

import application.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_auto_20201030_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='agree_to_coc',
            field=models.BooleanField(choices=[(True, 'Agree'), (False, 'Disagree')], default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='birthday',
            field=models.CharField(max_length=255, null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='application',
            name='interested_in_hacklahoma',
            field=models.BooleanField(choices=[(True, 'Agree'), (False, 'Disagree')], default=None, verbose_name='Are you interested in joining the Hacklahoma 2022 team?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_adult',
            field=models.BooleanField(choices=[(True, 'Agree'), (False, 'Disagree')], default=None, verbose_name='Please confirm you are 18 or older.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='liability_waiver',
            field=models.BooleanField(choices=[(True, 'Agree'), (False, 'Disagree')], default=None, verbose_name='Liability Waiver'),
        ),
        migrations.AlterField(
            model_name='application',
            name='mlh_authorize',
            field=models.BooleanField(choices=[(True, 'Agree'), (False, 'Disagree')], default=None, verbose_name='I authorize Major League Hacking to send me occasional messages about hackathons.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='photo_release',
            field=models.BooleanField(choices=[(True, 'Agree'), (False, 'Disagree')], default=None, verbose_name="I authorize Hacklahoma to release and photo's with me in it."),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, help_text='Companies will use this resume to offer interviews for internships and full-time positions.', null=True, upload_to=application.models.uuid_generator, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Upload your resume (PDF only)'),
        ),
    ]
