# Generated by Django 2.2.13 on 2020-10-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_auto_20201030_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='graduation_year',
            field=models.CharField(choices=[('N', 'N/A'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=4, null=True, verbose_name='What is your anticipated graduation year?'),
        ),
    ]
