# Generated by Django 5.1.6 on 2025-02-28 14:58

import application.filesize_validation
import application.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_auto_20241210_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.PositiveIntegerField(max_length=5, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='application',
            name='dietary_restrictions',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='grad_year',
            field=models.IntegerField(choices=[(2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], verbose_name='What is your anticipated graduation year?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(help_text='Companies will use this resume to offer interviews for internships and full-time positions.', upload_to=application.models.uuid_generator, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), application.filesize_validation.FileSizeValidator(max_filesize=2.5)], verbose_name='Upload your resume (PDF only)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='wares',
            field=models.CharField(choices=[('SW', 'Software'), ('HW', 'Hardware')], default='NA', max_length=8, null=True, verbose_name='TAMUhack will be partnering with IEEE to offer a dedicated hardware track and prizes. Participants can choose to compete in this track or in the general software tracks. Would you like to compete in the software or hardware track'),
        ),
    ]
