# Generated by Django 2.2.13 on 2020-10-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_auto_20201030_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='interested_in_hacklahoma',
            field=models.BooleanField(choices=[(True, 'Agree'), (False, 'Disagree')], default=None, help_text="We'll possibly reach out to you to join the executive team!", verbose_name='Are you interested in organizing the Hacklahoma 2022 event?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_adult',
            field=models.BooleanField(choices=[(True, 'Agree'), (False, 'Disagree')], default=None, verbose_name='I confirm I am 18 years or older.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='liability_waiver',
            field=models.BooleanField(choices=[(True, 'Agree'), (False, 'Disagree')], default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='num_hackathons_attended',
            field=models.CharField(max_length=22, null=True, verbose_name='How many hackathons have you attended?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='photo_release',
            field=models.BooleanField(choices=[(True, 'Agree'), (False, 'Disagree')], default=None, verbose_name='I authorize Hacklahoma to release photos with me in it.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question2',
            field=models.TextField(max_length=500, null=True, verbose_name='What workshops/activities do you want to see at Hacklahoma?'),
        ),
    ]
