# Generated by Django 5.1.6 on 2025-03-04 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0029_alter_application_age_and_more"),
        ("volunteer", "0004_remove_foodevent_restrictions_alter_foodevent_meal"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DietaryRestriction",
        ),
    ]
