# Generated by Django 2.2.13 on 2020-10-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_auto_20201031_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='shipping_address',
            field=models.BooleanField(default=None, help_text="This is completely optional! We'll use this to ship out snacks and swag directly to you participate in the hackathon!", verbose_name='Shipping Address'),
        ),
    ]
