# Generated by Django 5.1.6 on 2025-04-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_alter_application_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='application',
            name='dietary_restrictions',
            field=models.CharField(blank=True, default='none', max_length=255, verbose_name='Do you have any dietary restrictions?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='technology_experience',
            field=models.CharField(blank=True, max_length=255, verbose_name='What technology do you have experience with?'),
        ),
    ]
