# Generated by Django 2.2.13 on 2020-10-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_auto_20201031_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='shipping_address',
            field=models.BooleanField(choices=[(True, 'Agree'), (False, 'Disagree')], default=None, help_text="This is completely optional! We'll use this to ship out snacks and swag directly to you participate in the hackathon!", null=True, verbose_name='Shipping Address'),
        ),
    ]
