# Generated by Django 5.2.7 on 2025-11-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_alter_application_discovery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_rsvped',
            field=models.BooleanField(default=False),
        ),
    ]
