# Generated by Django 2.2.13 on 2020-10-31 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_auto_20201031_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='shipping_address',
            new_name='mailing_address',
        ),
    ]
