# Generated by Django 2.2.13 on 2020-10-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_auto_20201031_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='mailing_address',
        ),
        migrations.AddField(
            model_name='application',
            name='shipping_address',
            field=models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')], default=None, help_text='Note: US residents only.', verbose_name='Are you interested in geting snacks and swag shipped directly to you for your partitipation?'),
        ),
    ]
