# Generated by Django 2.2.13 on 2020-10-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_auto_20201031_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='shipping_address',
            field=models.CharField(blank=True, choices=[('Y', '')], default=None, help_text='Note: US residents only.', max_length=2, null=True, verbose_name='Are you interested in geting snacks and swag shipped directly to you for your partitipation?'),
        ),
    ]
