# Generated by Django 2.2.13 on 2020-10-31 08:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_auto_20201031_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='shipping_address',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Y', '')], default=None, help_text='Note: US residents only.', max_length=2, null=True, verbose_name='Are you interested in geting snacks and swag shipped directly to you for your partitipation?'),
        ),
    ]
