# Generated by Django 5.2.8 on 2025-12-15 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_alter_application_is_adult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-datetime_submitted']},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['datetime_submitted'], name='application_datetim_159202_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['school'], name='application_school__52084a_idx'),
        ),
    ]
