# Generated by Django 2.2.13 on 2020-11-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0039_auto_20201031_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.AddField(
            model_name='application',
            name='school_email',
            field=models.CharField(help_text='Please enter your school address ending in .edu to be considered. Contact us at team@hacklahoma.org for any exceptions.', max_length=255, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='application',
            name='shipping_address',
            field=models.BooleanField(choices=[(True, 'Agree'), (False, 'Disagree')], default=None, help_text='Note: US residents only and must submit a project', verbose_name='Would you like to have swag and snacks shipped directly to you?'),
        ),
    ]
