# Generated by Django 6.0 on 2026-01-21 03:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0039_alter_application_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdHocEmailBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('html_template', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ad hoc email batches',
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='grad_year',
            field=models.IntegerField(choices=[(2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031)], verbose_name='What is your anticipated graduation year?'),
        ),
    ]
