# Generated by Django 2.2.13 on 2020-11-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0040_auto_20201101_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='social_links',
            field=models.CharField(blank=True, help_text='Please separate links with a comma.', max_length=200, verbose_name="Point us to any social links you'd like us to look at while considering your application"),
        ),
    ]
