# Generated by Django 6.0.2 on 2026-03-09 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0040_adhocemailbatch_alter_application_grad_year'),
        ('team', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='team.team'),
        ),
    ]
