# Generated by Django 6.0.3 on 2026-04-22 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_application_team'),
        ('team', '0005_remove_team_captain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('is_captain', True)), fields=('team',), name='unique_team_captain'),
        ),
    ]
