# Generated by Django 2.2.13 on 2020-11-10 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_remove_application_is_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='school_email',
            field=models.CharField(help_text='Please enter your school address ending in .edu to be considered. Contact us at team@hacklahoma.org for any exceptions.', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address ending in .edu', regex='^([A-Za-z0-9_\\.-]+\\@[\\da-z\\.-]+\\.edu)$')], verbose_name='email address'),
        ),
    ]
