# Generated by Django 6.0.3 on 2026-09-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_alter_application_wares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='wares',
            field=models.CharField(choices=[('SW', 'Software'), ('HW', 'Hardware')], default='NA', max_length=8, null=True, verbose_name='The event will be offering a dedicated hardware track and prizes. Participants can choose to compete in this track or in the general software tracks. Would you like to compete in the software or hardware track?'),
        ),
    ]
