# Generated by Django 2.2.13 on 2020-12-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_auto_20201109_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='discord_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
