# Generated by Django 6.0.3 on 2026-09-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_alter_application_wares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_adult',
            field=models.BooleanField(blank=True, choices=[(True, 'Agree')], default=None, help_text='Please note that applicants under 18 must prove that they are a current student at Texas A&M.', null=True, verbose_name='Please confirm you are 18 or older OR you are under 18 and are a current student at TAMU.'),
        ),
    ]
