# Generated by Django 2.2.13 on 2022-01-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteer", "0002_auto_20200413_1240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodevent",
            name="meal",
            field=models.CharField(
                choices=[
                    ("B", "Breakfast"),
                    ("L", "Lunch"),
                    ("D", "Dinner"),
                    ("MS", "Midnight Snack"),
                    ("B2", "Breakfast (Day 2)"),
                    ("L2", "Lunch (Day 2)"),
                    ("B_G", "Breakfast - [Gluten Free]"),
                    ("L_G", "Lunch - [Gluten Free]"),
                    ("D_G", "Dinner - [Gluten Free]"),
                    ("MS_G", "Midnight Snack - [Gluten Free]"),
                    ("B2_G", "Breakfast (Day 2) - [Gluten Free]"),
                    ("L2_G", "Lunch (Day 2) - [Gluten Free]"),
                    ("B_V", "Breakfast - [Vegan]"),
                    ("L_V", "Lunch - [Vegan]"),
                    ("D_V", "Dinner - [Vegan]"),
                    ("MS_V", "Midnight Snack - [Vegan]"),
                    ("B2_V", "Breakfast (Day 2) - [Vegan]"),
                    ("L2_V", "Lunch (Day 2) - [Vegan]"),
                ],
                max_length=14,
            ),
        ),
    ]
