# Generated by Django 2.2.2 on 2019-06-21 04:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='adult',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Are you at least 18 or older?'),
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name="What's your first name?"),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name="What's your last name?"),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.IntegerField(default='0', verbose_name="What's the best phone number to reach you?"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='race',
            field=models.CharField(choices=[('American Indian', 'American Indian or Alaskan Native'), ('Asian', 'Asian'), ('Black', 'Black or African-American'), ('Hispanic', 'Hispanic or Latino White'), ('Native Hawaiian', 'Native Hawaiian or other Pacific Islander'), ('White', 'White or Caucasian'), ('Two Races', 'Two or more races'), ('NA', 'Decline to self-identify')], default='NA', max_length=41, verbose_name='What race do you identify with?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='shirt_size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='NA', max_length=3, verbose_name='Shirt size?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='classification',
            field=models.CharField(choices=[('U1', 'U1'), ('U2', 'U2'), ('U3', 'U3'), ('U4', 'U4')], max_length=2, verbose_name='What classification are you?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='dietary_restrictions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Halal', 'Halal'), ('Kosher', 'Kosher'), ('Food Allergies', 'Food Allergies')], max_length=44, verbose_name='Do you have any dietary restrictions that we should know about?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('NA', 'Prefer not to disclose')], max_length=2, verbose_name="What's your gender?"),
        ),
        migrations.AlterField(
            model_name='application',
            name='grad_year',
            field=models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], verbose_name='What is your anticipated graduation date?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='major',
            field=models.CharField(max_length=50, verbose_name="What's your major?"),
        ),
        migrations.AlterField(
            model_name='application',
            name='num_hackathons_attended',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='How many hackathons have you attended?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='previous_attendant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Have you attended Howdy Hack before?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='', verbose_name='Provide us a copy of your most recent resume so we can get you connected with companies'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tamu_student',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Are you a Texas A&M student?'),
        ),
    ]
