# Generated by Django 2.2.3 on 2019-07-17 05:04

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='mlh_coc',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(True, 'Agree')], default='', max_length=4, verbose_name='I agree to the MLH Code of Conduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='adult',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(True, 'Agree')], default=None, help_text='Please note that freshmen under 18 must be accompanied by an adult or prove that they go to Texas A&M.', max_length=4, verbose_name='Please confirm you are 18 or older'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[(None, '-- Select Option --'), ('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('NA', 'Prefer not to disclose'), ('Other', 'Other')], max_length=2, verbose_name="What's your gender?"),
        ),
        migrations.AlterField(
            model_name='application',
            name='major',
            field=models.CharField(choices=[(None, '-- Select Option --'), ('Accounting', 'Accounting'), ('Actuarial Science', 'Actuarial Science'), ('Advertising', 'Advertising'), ('Agriculture', 'Agriculture'), ('Agricultural and Biological Engineering', 'Agricultural and Biological Engineering'), ('Agricultural Business Management', 'Agricultural Business Management'), ('Agriculture Economics', 'Agriculture Economics'), ('Animal Bioscience', 'Animal Bioscience'), ('Animal Sciences', 'Animal Sciences'), ('Anthropology', 'Anthropology'), ('Applied Mathematics', 'Applied Mathematics'), ('Archaeology', 'Archaeology'), ('Architectural Engineering', 'Architectural Engineering'), ('Architecture', 'Architecture'), ('Art History', 'Art History'), ('Studio Art', 'Studio Art'), ('Art Education', 'Art Education'), ('Biobehavioral Health', 'Biobehavioral Health'), ('Biochemistry', 'Biochemistry'), ('Bioengineering', 'Bioengineering'), ('Biology', 'Biology'), ('Biophysics', 'Biophysics'), ('Biotechnology', 'Biotechnology'), ('Business Administration and Management', 'Business Administration and Management'), ('Business Logistics', 'Business Logistics'), ('Chemical Engineering', 'Chemical Engineering'), ('Chemistry', 'Chemistry'), ('Children', 'Children'), ('Civil Engineering', 'Civil Engineering'), ('Computer Engineering', 'Computer Engineering'), ('Computer Science', 'Computer Science'), ('Crime, Law, and Justice', 'Crime, Law, and Justice'), ('Dance', 'Dance'), ('Earth Sciences', 'Earth Sciences'), ('Economics', 'Economics'), ('Electrical Engineering', 'Electrical Engineering'), ('Elementary and Kindergarten Education', 'Elementary and Kindergarten Education'), ('Engineering Science', 'Engineering Science'), ('English', 'English'), ('Environmental Systems Engineering', 'Environmental Systems Engineering'), ('Environmental Sciences', 'Environmental Sciences'), ('Environmental Resource Management', 'Environmental Resource Management'), ('Film and Video', 'Film and Video'), ('Finance', 'Finance'), ('Food Science', 'Food Science'), ('Forest Science', 'Forest Science'), ('Forest Technology', 'Forest Technology'), ('General Science', 'General Science'), ('Geography', 'Geography'), ('Geosciences', 'Geosciences'), ('General Engineering', 'General Engineering'), ('Graphic Design and Photography', 'Graphic Design and Photography'), ('Health and Physical Education', 'Health and Physical Education'), ('Health Policy and Administration', 'Health Policy and Administration'), ('History', 'History'), ('Horticulture', 'Horticulture'), ('Hotel, Restaurant, and Institutional Management', 'Hotel, Restaurant, and Institutional Management'), ('Human Development and Family Studies', 'Human Development and Family Studies'), ('Individual and Family Studies', 'Individual and Family Studies'), ('Industrial Engineering', 'Industrial Engineering'), ('Information Sciences and Technology', 'Information Sciences and Technology'), ('Journalism', 'Journalism'), ('Kinesiology', 'Kinesiology'), ('Landscape Architecture', 'Landscape Architecture'), ('Law Enforcement and Correction', 'Law Enforcement and Correction'), ('Marine Biology', 'Marine Biology'), ('Marketing', 'Marketing'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Media Studies', 'Media Studies'), ('Meteorology', 'Meteorology'), ('Microbiology', 'Microbiology'), ('Mineral Economics', 'Mineral Economics'), ('Modern Languages', 'Modern Languages'), ('Music Education', 'Music Education'), ('Nuclear Engineering', 'Nuclear Engineering'), ('Nursing', 'Nursing'), ('Nutrition', 'Nutrition'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Physiology', 'Physiology'), ('Political Science', 'Political Science'), ('Pre-medicine', 'Pre-medicine'), ('Psychology', 'Psychology'), ('Public Relations', 'Public Relations'), ('Real Estate', 'Real Estate'), ('Recreation and Parks', 'Recreation and Parks'), ('Rehabilitation Services', 'Rehabilitation Services'), ('Religious Studies', 'Religious Studies'), ('Secondary Education', 'Secondary Education'), ('Sociology', 'Sociology'), ('Social Work', 'Social Work'), ('Special Education', 'Special Education'), ('Speech Communication', 'Speech Communication'), ('Speech Pathology and Audiology/Communication Disorder', 'Speech Pathology and Audiology/Communication Disorder'), ('Statistics', 'Statistics'), ('Telecommunications', 'Telecommunications'), ('Theater', 'Theater'), ('Wildlife and Fishery Science', 'Wildlife and Fishery Science'), ('Wildlife Technology', 'Wildlife Technology'), ("Women's Studies", "Women's Studies")], max_length=50, verbose_name="What's your major?"),
        ),
        migrations.AlterField(
            model_name='application',
            name='race',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('American Indian', 'American Indian or Alaskan Native'), ('Asian', 'Asian'), ('Black', 'Black or African-American'), ('Hispanic', 'Hispanic or Latino White'), ('Native Hawaiian', 'Native Hawaiian or other Pacific Islander'), ('White', 'White or Caucasian'), ('NA', 'Decline to self-identify'), ('Other', 'Other')], max_length=41, verbose_name='What race(s) do you identify with?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(help_text='Companies will use this resume to offer interviews for internships and full-time positions.', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Upload your resume'),
        ),
    ]
