# Generated by Django 2.2.2 on 2019-07-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cool_prize',
            field=models.TextField(max_length=500, verbose_name="What is a cool prize you'd like to win at Howdy Hack?"),
        ),
    ]
