# Generated by Django 2.2.2 on 2019-06-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0002_auto_20190620_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='phone_number',
        ),
    ]
