# Generated by Django 2.2.3 on 2019-07-17 05:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0002_auto_20190717_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='adult',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Agree', 'Agree')], default=None, help_text='Please note that freshmen under 18 must be accompanied by an adult or prove that they go to Texas A&M.', max_length=5, verbose_name='Please confirm you are 18 or older'),
        ),
        migrations.AlterField(
            model_name='application',
            name='mlh_coc',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Agree', 'Agree')], max_length=5, verbose_name='I agree to the MLH Code of Conduct'),
        ),
    ]
