# Generated by Django 2.2.2 on 2019-07-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0002_auto_20190702_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='shirt_size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default=None, max_length=3, verbose_name='Shirt size?'),
        ),
    ]
