# Generated by Django 2.2.3 on 2019-07-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0003_auto_20190717_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='adult',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, help_text='Please note that freshmen under 18 must be accompanied by an adult or prove that they go to Texas A&M.', verbose_name='Please confirm you are 18 or older'),
        ),
        migrations.AlterField(
            model_name='application',
            name='mlh_coc',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, verbose_name='I agree to the MLH Code of Conduct'),
        ),
    ]
