# Generated by Django 5.1.6 on 2025-02-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="admitted",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
