# Generated by Django 5.1.6 on 2025-03-22 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_admitted'),
        ('user', '0002_remove_user_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
