# Generated by Django 6.0.3 on 2026-04-22 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
    ]
