# Generated by Django 6.0.3 on 2026-09-09 02:11

from django.db import migrations, models

import team.codes


def assign_codes(apps, schema_editor):
    teams = apps.get_model("team", "Team").objects.using(schema_editor.connection.alias)
    used = set()
    for existing_team in teams.iterator():
        code = team.codes.generate_team_code()
        while code in used:
            code = team.codes.generate_team_code()
        used.add(code)
        teams.filter(pk=existing_team.pk).update(code=code)


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0005_remove_team_captain"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="code",
            field=models.CharField(null=True, editable=False, max_length=64),
        ),
        migrations.RunPython(assign_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="team",
            name="code",
            field=models.CharField(
                default=team.codes.generate_team_code, editable=False, max_length=64
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("code",),
                name="unique_active_team_code",
            ),
        ),
    ]
