# Generated by Django 5.2.2 on 2025-08-25 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgesmentors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judge',
            old_name='is_tamu_faculty',
            new_name='is_faculty',
        ),
    ]
